name: Setup
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        registry-url: https://registry.npmjs.org
        cache: pnpm

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Install node modules
      run: pnpm install
      shell: bash

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v3

    - run: |
        echo "nx using following shas:"
        echo "BASE: ${{ env.NX_BASE }}"
        echo "HEAD: ${{ env.NX_HEAD }}"
      shell: bash
