FROM mcr.microsoft.com/playwright:v1.29.0-focal

USER root

# Add the Foundry CLI to the PATH
RUN curl -L https://foundry.paradigm.xyz | bash
ENV PATH "$PATH:/root/.foundry/bin"
RUN foundryup \
  && forge --version \
  && anvil --version \
  && cast --version

WORKDIR /monorepo-e2e

RUN npm i pnpm@7.18.2 --global

ENV NX_DAEMON=false

COPY ./ /monorepo-e2e
RUN pnpm i && pnpm build

CMD ["pnpm", "-F", "@roninjin10/e2e", "test"]
