version: '3'

services:
  # React App
  example-ui:
    extends:
      file: docker-compose.base.yml
      service: base-app
    command: pnpm nx serve @stax/example-ui
    ports:
      - 3000:3001

  # Fastify server
  example-server:
    extends:
      file: docker-compose.base.yml
      service: base-app
    command: pnpm nx serve @stax/example-server
    ports:
      - 7300:7301
