[profile.default]
# The source directory
src = 'packages/contracts/src'
# The test directory
test = 'packages/contracts/test'
# We need to build seperate artifacts for forge and hh, because they each expect a different
# structure for the artifacts directory.
# The artifact directory
out = 'packages/contracts/build'
# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200
# The metadata hash can be removed from the bytecode by setting "none"
bytecode_hash = "none"

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
goerli = "${RPC_URL_GOERLI}"
optimism = "${RPC_URL_OPTIMISM}"
arbitrum = "${RPC_URL_ARBITRUM}"
polygon = "${RPC_URL_POLYGON}"

[etherscan]
mainnet = {key = "${ETHERSCAN_KEY}"}
goerli = {key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api"}
optimism = {key = "${OPTIMISM_ETHERSCAN_KEY}", url = "https://api-optimistic.etherscan.io/api"}
arbitrum = {key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api"}
polygon = {key = "${POLYGONSCAN_KEY}", url = "https://api.polygonscan.com/api"}
