name: Setup Docker
runs:
  using: composite
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
