name: Publish docker image no push

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    environment: dockerhub
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Setup docker'
        uses: ./.github/actions/setup-docker
        secrets:
          username: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN_SECRET }}

      - name: Publish server image to docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: 'willcory10/roninjin10-example-server:latest'
