on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

name: Publish no push

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: 'Setup'
        uses: ./.github/actions/setup

      - name: Run build
        run: pnpm build:ci
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

      - name: Simulating publish package on NPM 📦
        run: pnpm release:dry
